export * from "./About";
export * from "./Contact";
export * from "./Footer";
export * from "./Header";
export * from "./Home";
export * from "./Projects";
export * from "./Main";
export * from "./Skills";
export * from "./NavBar";
